### ISSUE TITLE
Unexpected and inconsistent `holdWhen()` behavior

### ISSUE THREAD

**Issue by timmolendijk** [baconjs/bacon.js#597] opened 2015-06-01 20:18 UTC
In the [API docs](https://baconjs.github.io/api.html#stream-holdwhen) `.holdWhen()` is said to:

> pauses and buffers the event stream if last event in valve is truthy

When I tried to reproduce this behavior I couldn't, and on top of that I found v0.7.60 to behave very differently from v0.7.59.

My code sample is as follows:
```js
Bacon.fromBinder(function (sink) {
  sink(new Bacon.Initial());
  sink(new Bacon.Error());
  sink(new Bacon.Next());
  sink(new Bacon.End());
  return function () {};
}).holdWhen(
  Bacon.later(2000, false).startWith(true)
).subscribe(function (event) {
  $('#log').append(event.constructor.name + "\n");
});
```

The output in `#log` that I had been expecting:
```
<2 sec delay>
Initial
Error
Next
End
```

Instead, what I ended up getting:

The result under v0.7.59 ([demo](http://output.jsbin.com/kuzivuhazo/1/quiet)):
```
Error
<2 sec delay>
End
```

The result under v0.7.60 ([demo](http://output.jsbin.com/kuzivuhazo/2/quiet)):
```
Initial
Error
Next
End
<no delays at any point in time>
```

I did look into the corresponding unit tests, as those are succeeding, but I had a hard time replicating them as they depend on some factory methods (`expectStreamTimings()` and `series()`) which are unfamiliar to me.

Two questions:

* What _is_ the expected behavior of `holdWhen()` in the case of my code sample?
* What explains the difference between v0.7.59 and v0.7.60 (and possibly the expected behavior)?

**Comment by raimohanska** [comment] 2015-06-02 05:19
I'd say the expected behavior would be

Error
<2 sec delay>
Initial
Next End

Because the Error events are always passed through directly.

This is once again an issue with synchronous sources. If you delay the source, it'll work.

The difference to 0.7.59 is that holdWhen has been completely re-implemented.

It would make sense to fix this, of course.

**Comment by raimohanska** [comment] 2015-06-02 05:38
Ok, fixed in 0.7.61, with 2 more test cases. Will you pls chec if it works for you.

**Comment by timmolendijk** [comment] 2015-06-02 09:58
Works, except that the `Initial` has been transformed into a `Next`: [demo](http://output.jsbin.com/gozoqufiko/1/quiet)

**Comment by raimohanska** [comment] 2015-06-02 10:36
Thanks. Well, Initial is a corner case: EventStreams should never emit Initial events. It gets converted on the way... somewhere :)

**Comment by raimohanska** [comment] 2015-06-02 10:37
Anyway, this seems to be fixed now. Please re-open if you disagree.

**Closed by raimohanska** 2015-06-02 10:37 UTC

**Comment by timmolendijk** [comment] 2015-06-02 11:14
Yes, agree.

It does beg the question what to do with `Initial` events in general though, for which I opened a [new issue](#598).
