### ISSUE TITLE
Coffeescript to ES6

### ISSUE THREAD

**Issue by GianlucaGuarini** [baconjs/bacon.js#492] opened 2014-12-11 19:31 UTC
What do you think if we move the project forward migrating the current coffeescript code to javascript next? I think we could transpile it using https://6to5.github.io/

**Comment by AlexGalays** [comment] 2015-01-06 20:19
+1 for a rewrite to ES6/ES5, or even vanilla JS + sweet.js macros.
CS is quite alien for many JS devs.

**Comment by GianlucaGuarini** [comment] 2015-01-07 23:23
I start getting some memory improvements migrating to ES6 https://github.com/baconjs/bacon.js/issues/446#issuecomment-69110624

**Comment by GianlucaGuarini** [comment] 2015-01-08 23:18
I have checked the Baconjs generated from coffeescript and the other one coming from my [migration/es6 fork](https://github.com/baconjs/bacon.js/tree/migration/es6). Here you can run the benchmark by yourself http://jsperf.com/bacon-coffeescript-vs-bacon-es6 and check the results
It looks that the es6 output is faster on firefox and slower on chrome. In any case I think I need someone who helps me during the migration translating the whole library entirely to es6.

**Comment by lautis** [comment] 2015-01-08 23:43
With Node 0.10 performance seems pretty badly reduced on the ES6 branch, but Node 0.10 based on quite old Chrome. Replacing `this.subscribe.bind(this)` with a closured version might improve that as `Function.prototype.bind` is [pretty slow](http://jsperf.com/bind-vs-closure-setup) at least on older Chromes.

**Comment by sebmck** [comment] 2015-01-08 23:45
@lautis That benchmark is incorrect since `var test = function(){ return this };` in the self test should be `var test = function(){ return self; };`.

**Comment by lautis** [comment] 2015-01-08 23:56
I changed the link to point to a later revision that seems to be a bit less wrong.

**Comment by GianlucaGuarini** [comment] 2015-01-09 07:13
Ok I will update the branch using replacing the native bind functions to get faster performances also on Chrome

**Comment by GianlucaGuarini** [comment] 2015-01-10 14:14
@lautis changing the native bind to the wrapped one the es6 branch is a bit faster than the master. I hope that with my next updates, splitting the source code into smaller modules it will become also a bit more readable.

**Comment by GianlucaGuarini** [comment] 2015-01-13 21:46
I am sorry guys but I must give up migrating Baconjs to es6. 
Here a list of reasons:
- There are too many weekly changes to the original Coffeescript source code even on the project scaffolding (see assemble.js) deprecating the code I am working on too quickly
- 6to5 became on any new release more and more unstable/unusable relying on external polyfills and polluting the output code, a library like Bacon cannot include several polyfills/runtime in its source code
- I am the only one working on this branch I didn't get any help working on the migration and it became quickly too much work
- there is too much Coffeescript here. The grunt tasks, the tests and the source code are all written in Coffeescript so probably you don't really want/need to switch to pure javascript just for the glam
 
I learned a lot reading the Baconjs source code but I've also understood that a project like Rxjs fits more to my needs.

**Comment by sebmck** [comment] 2015-01-13 21:49
@GianlucaGuarini 

> 6to5 became on any new release more and more unstable/unusable relying on external polyfills and polluting the output code, a library like Bacon cannot include several polyfills/runtime in its source code

That's factually incorrect. 6to5 has actually become **less** reliant on polyfill and shim methods. The output code has been coming less and less verbose and with features such as [loose mode](https://github.com/6to5/6to5/issues/465) that outputs simpler and faster code but is less spec compliant I take extreme issue with those kind of statements. There are only a few features that require `Array.from` and `Symbol` polyfills see the [caveats](http://6to5.org/docs/caveats/) and that's only to support all iterables for spec compliancy. There's even a mention in the [FAQ](http://6to5.org/docs/faq/#why-are-there-array-from-and-symbol-in-my-code-these-don-t-exist-) about how you can use these features **without** requiring a global polluting polyfill.

**Comment by GianlucaGuarini** [comment] 2015-01-13 22:06
@sebmck don't you think that for something simple like:
```javascript
// es6
for (var item of array) {
//...
}
```
an output like this (+ a huge Symbol polyfill ) :
```javascript
// 6to5 output
for (var _iterator = array[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
  var item = _step.value;
}
```
is a bit too much?
It cannot compete against the coffeescript output
```javascipt
var _i, _len;
for (_i = 0, _len = array.length; _i < _len; _i++) {
}
```

**Comment by thejameskyle** [comment] 2015-01-13 22:11
Hey @GianlucaGuarini, I can imagine why that would be frustrating. However, it needs to be the compiled 6to5 output in order to properly follow the ES6 specification. This isn't a stability issue, it's by design.

We've been looking into how people can opt-in to a simpler output which ignores various parts of the spec. This is what @sebmck meant by loose mode, and it's likely what you are looking for.

**Comment by sebmck** [comment] 2015-01-13 22:12
@GianlucaGuarini ES6 `for...of` is not equivalent to the CoffeeScript `for...of`. In ES6 it's to iterate over an Iterator, which can be a string, array, or an object that defines how it's supposed to be iterated over. Your example is comparing CoffeeScript `for...in` with ES6 `for...of` which is functionally different.

**Comment by GianlucaGuarini** [comment] 2015-01-13 22:35
@sebmck 
in case of an array it's clear that the iteration is over its items so probably the output could be simpler, the Symbol must be probably output mostly for Set and Maps. In any case In the previous 6to5 releases this problem was not there.
@thejameskyle 
The problem is that no library can be developed including polyfills directly in the source code if before it was working even on IE6 as standalone script.

**Comment by lautis** [comment] 2015-01-13 22:40
@GianlucaGuarini that's unfortunate :crying_cat_face: (and understandable, porting over patches isn't exactly the most exciting job). We'll need to be more focused if we want to get this done.

**Comment by thejameskyle** [comment] 2015-01-13 22:57
> in case of an array it's clear that the iteration is over its items so probably the output could be simpler

That would only work when we know a value is an array literal.

```js
function(items) {
  for (let item of items) {
    // no way of knowing items is an array.
  }
}
```

**Comment by sebmck** [comment] 2015-01-13 23:05
@sebmck

> in case of an array it's clear that the iteration is over its items so probably the output could be simpler

You can't keep track of types unless they're inlined as literals.

> the Symbol must be probably output mostly for Sets and Maps. In any case In the previous 6to5 releases this problem was not there.

It's been present since the inclusion of the for of transformer. See 6to5/6to5@b0cfbb20ca2340193700e4e0c780d78713b16c31.

As I said before, 6to5 has ways to facilitate the inclusion of these methods and native types without polluting the global scope with a polyfill. See the [FAQ](http://6to5.org/docs/faq/#why-are-there-array-from-and-symbol-in-my-code-these-don-t-exist-) and [coreAliasing](http://6to5.org/docs/usage/transformers/#core-aliasing).

**Comment by phadej** [comment] 2015-01-14 04:05
Let's see if the `assemble.js` could be changed to accept both *coffeescript* and *es6* parts. Then we don't need to do everything at once. And we can use work @GianlucaGuarini has already done!

**Comment by phadej** [comment] 2015-01-14 05:18
Here is working PoC: https://github.com/baconjs/bacon.js/pull/526

**Comment by GianlucaGuarini** [comment] 2015-01-14 08:00
@sebmck 
> It's been present since the inclusion of the for of transformer. See 6to5/6to5@b0cfbb2.

Oups sorry :D then probably I have imagined that

BTW It's clear that 6to5 it's an awesome tool, but I am not sure in this case It can compete against the clear and dry coffeescript source code used for the Baconjs library

**Comment by sebmck** [comment] 2015-01-14 08:01
@GianlucaGuarini By default, definently. [Loose mode](6to5/6to5#465) however will produce better, if not equivalently fast code.

**Comment by GianlucaGuarini** [comment] 2015-01-14 08:08
looking forward to try it out thanks for your support

**Comment by raimohanska** [comment] 2015-02-23 20:06
Closing for now, until some progress seen, if any...

**Closed by raimohanska** 2015-02-23 20:06 UTC
