### ISSUE TITLE
Stream stops out of blue with no indication.

### ISSUE THREAD

**Issue by eguneys** [baconjs/bacon.js#519] opened 2015-01-08 21:55 UTC
I have an application using baconjs, sometimes in a long stream application hangs unpredictably, I can't locate what happens. The only clue I have is:

When I do a `stream.log()`, It gives a bunch of values, and then application exists. There is no `<error>` or `<end>` indication. And the values I get are inconsistent, so the stream doesn't end in a particular point.

Please help me out, could this be a bacon bug, is it ever OK for a bacon stream to end without indication? Any hints are appreciated.

**Comment by AgentME** [comment] 2015-01-09 18:45
> Please help me out, could this be a bacon bug, is it ever OK for a bacon stream to end without indication? 

Streams don't have to end. A not-ended stream can be garbage-collected perfectly fine. Think of the stream `Bacon.fromEventTarget(someElement, 'someEvent')` and what happens when `someElement` is removed from the page and has no one else referring to it.

Nodejs ends the process when there's nothing left to do. If a run of the event loop has finished, and there's nothing further scheduled like I/O or timeouts, the process will end.

**Comment by eguneys** [comment] 2015-01-09 19:28
I have 3 examples Bacon behaves differently and it is confusing and hard to debug. I need proper error handling examples:

```js
var errorish = Bacon.fromPromise(new RSVP.Promise(function(resolve) {
  resolve([1,2,3]);
})).flatMap(Bacon.fromArray).flatMapConcat(function() {
  throw 10;
});

// ends without indication
//errorish.log();

var goodError = Bacon.fromArray([1,2,3]).flatMapConcat(function() {
  throw 10;
});

// throws
//goodError.log();

var errorInPromise = Bacon.fromArray([1,2,3]).flatMapConcat(function() {
  return Bacon.fromPromise(new RSVP.Promise(function(resolve) {
    throw 10;
  }));
});

// error event
//errorInPromise.log();
```

I would expect error events to be streamed on each of these situations, especially the first one ending with no indication is really ugly, I think streams should never end without any indication of `<error>` or `<end>`.

**Comment by AgentME** [comment] 2015-01-09 19:51
Oh, those are problems. Bacon shouldn't hide exceptions. (Bacon never auto-converts exceptions to Bacon.Error events; the exceptions should be thrown somewhere.) This is similar to the older issue #488.

**Comment by AgentME** [comment] 2015-01-09 19:52
This is the same as issue #511.

**Comment by phadej** [comment] 2015-01-09 19:53
By quick look the first and the second cases will behave in the same way after https://github.com/baconjs/bacon.js/pull/518 is merged.

The last case **is** different by design. Bacon.js doesn't catch any exceptions (and turn them into error events). In this aspect Bacon.js is different from Promises. It's a conscious design choice. cc @raimohanska

**Comment by AgentME** [comment] 2015-01-09 20:11
You can get more useful debugging information from your first example by setting an uncaught Promise rejection handler. I consider this necessary whenever working with promises. (It is still an issue that the `throw 10` is treated as a promise rejection, but setting this handler stops you from missing exceptions in non-Bacon-related Promise code too.)

```javascript
var Bacon = require('baconjs');
var RSVP = require('rsvp');

RSVP.on('error', function(err) {
  console.error('uncaught error', err);
});

var errorish = Bacon.fromPromise(new RSVP.Promise(function(resolve) {
  resolve([1,2,3]);
})).flatMap(Bacon.fromArray).flatMapConcat(function() {
  throw 10;
});

errorish.log();
```

**Closed** 2015-01-15 22:23 UTC
